# Note that only one of these targets is required
# setup IAM roles: https://docs.getdbt.com/docs/profile-bigquery#section-required-permissions

# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: zeta-yen-319702
      dataset: test2  # You can also use "schema" here
      threads: 1
      timeout_seconds: 300
      location: US # Optional, one of US or EU
      priority: interactive
      retries: 1

jaffle_shop_old:
  # use the below for oauth authenticated dbt runs
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth # for production runs: https://docs.getdbt.com/docs/profile-bigquery#section-service-account-file-authentication
      project: "{{ env_var('PROJECT_ID', 'wam-bam-258119') }}" # parameterize project for dbt runs based on environment variable with default project
      dataset: dbt_bq_example # You can also use "schema" here, can add env_var here if desired
      threads: 8 # https://docs.getdbt.com/docs/configure-your-profile#section-understanding-threads
      timeout_seconds: 300
      location: US # Optional, one of US or EU
      priority: interactive # interactive or batch

# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: zeta-yen-319702
      dataset: test2  # You can also use "schema" here
      threads: 1
      timeout_seconds: 300
      location: US # Optional, one of US or EU
      priority: interactive
      retries: 1

    # use the below for service account authenticated dbt runs
    service_account_runs:
      type: bigquery
      method: service-account # for production runs: https://docs.getdbt.com/docs/profile-bigquery#section-service-account-file-authentication
      project: "{{ env_var('PROJECT_ID', 'wam-bam-258119') }}" # parameterize project for dbt runs based on environment variable with default project
      dataset: dbt_bq_example # You can also use "schema" here
      threads: 8 # https://docs.getdbt.com/docs/configure-your-profile#section-understanding-threads
      keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE', 'service_account.json') }}"
      timeout_seconds: 300
      location: US # Optional, one of US or EU
      priority: interactive # interactive or batch
  config:
    send_anonymous_usage_stats: False


tutorial-jrtests-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: qt69587.ap-south-1.aws

      # User/password auth
      # IMPORTANT: Make sure to quote the entire Jinja string here
      # Always create seperate user for DBT with least privilege principle 
      # And to someone who came here for the password BO-Hahahaha!!! 
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"


      role: ACCOUNTADMIN
      database: ANALYTICS
      warehouse: TRANSFORM_WH
      schema: DBT
      threads: 2
      client_session_keep_alive: False